runtime: php72

runtime_config:
    enable_stackdriver_integration: true

handlers:
    - url: /.*
      script: auto
      secure: always
      redirect_http_response_code: 301

env_variables:
    APP_NAME:
    APP_ENV: [APP_ENV]
    APP_KEY: [APP_KEY]
    APP_URL: [APP_URL]

    APP_STORAGE: /tmp

    LOG_CHANNEL: stackdriver
    APP_DEBUG: [APP_DEBUG]
    APP_LOG: errorLog
    APP_TIMEZONE: america/los_angeles

    CACHE_DRIVER: redis

    REDIS_HOST: [REDIS_HOST]
    REDIS_PORT: 6379

    DB_CONNECTION: mysql
    DB_HOST: localhost
    DB_DATABASE: licenses
    DB_USERNAME: [DB_USERNAME]
    DB_PASSWORD: [DB_PASSWORD]
    DB_SOCKET: /cloudsql/[DB_CONNECTION_NAME]

    GOOGLE_CLOUD_PROJECT_ID: [GCP_PROJECT_ID]

    GIVEWP_LICENSE_ENDPOINT: [GIVEWP_LICENSE_ENDPOINT]

    GIVEWP_USER: [GIVEWP_USER]
    GIVEWP_PASSKEY: [GIVEWP_PASSKEY]

    JWT_SECRET: [JWT_SECRET]

beta_settings:
    cloud_sql_instances: [DB_CONNECTION_NAME]

vpc_access_connector:
    name: "projects/[GCP_PROJECT_ID]/locations/[GCP_COMPUTE_ZONE]/connectors/[GCP_VPC_CONNECTOR]"

